import math
import json

# resolution can be changed (within reasonable limits)
WIN_WIDTH = 1920
WIN_HEIGHT = 1080

FRAMERATE = 60
SPEED = 2 * math.floor(WIN_HEIGHT / 720) if WIN_HEIGHT > 720 else 1

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

PACMANHEIGHT = WIN_HEIGHT // 32 - 5
PACMANWIDTH = WIN_HEIGHT // 32 - 5
PACMANLIVES = 3

POINTRADIUS = PACMANHEIGHT // 4
POINTCOLOR = (250, 47, 116)

BRICKSHEIGHT = WIN_HEIGHT // 32
BRICKSWIDTH = WIN_HEIGHT // 32
BRICKSCOLOR = (28, 89, 208)

STARTMAPWIDTH = 5 * BRICKSWIDTH
STARTGHOSTPOSITION = (STARTMAPWIDTH + int(BRICKSWIDTH * 16), BRICKSHEIGHT * 12)
STARTPACMANPOSITION = (STARTMAPWIDTH + int(BRICKSWIDTH * 15.7), BRICKSHEIGHT * 18)
GHOSTHEIGHT = WIN_HEIGHT // 32
GHOSTWIDTH = WIN_HEIGHT // 32
GHOSTPOSITION = [[STARTMAPWIDTH + BRICKSWIDTH * 13, BRICKSHEIGHT * 14],
                 [STARTMAPWIDTH + BRICKSWIDTH * 13, BRICKSHEIGHT * 16],
                 [STARTMAPWIDTH + BRICKSWIDTH * 18, BRICKSHEIGHT * 14],
                 [STARTMAPWIDTH + BRICKSWIDTH * 18, BRICKSHEIGHT * 16]]
TEXTSIZE = WIN_HEIGHT // 20
TEXTPOINTSCOORDS = (WIN_WIDTH - BRICKSWIDTH * 5, WIN_HEIGHT // 20)
TEXTLIVESCOORDS = (WIN_WIDTH - BRICKSWIDTH * 5, WIN_HEIGHT // 20 + TEXTSIZE * 2)
TIMERPOSITION = (WIN_WIDTH - BRICKSWIDTH * 5, WIN_HEIGHT // 20 + TEXTSIZE * 4)
WINORLOSSTEXTPOSITION = (WIN_WIDTH - BRICKSWIDTH * 10, WIN_HEIGHT // 20 + TEXTSIZE * 8)
ESCAPEPOSITION = (WIN_WIDTH - BRICKSWIDTH * 10, WIN_HEIGHT // 20 + TEXTSIZE * 10)


BUTTONWIDTH = 200
BUTTONHEIGHT = 150
BUTTONCOLOR = (153, 255, 153)
BUTTONPOSITION = [[WIN_WIDTH // 2 - BUTTONWIDTH // 2, WIN_HEIGHT // 2 - BUTTONHEIGHT // 2 - 300],
                  [WIN_WIDTH // 2 - BUTTONWIDTH // 2, WIN_HEIGHT // 2 - BUTTONHEIGHT // 2 - 100],
                  [WIN_WIDTH // 2 - BUTTONWIDTH // 2, WIN_HEIGHT // 2 - BUTTONHEIGHT // 2 + 100],
                  [WIN_WIDTH // 2 - BUTTONWIDTH // 2, WIN_HEIGHT // 2 - BUTTONHEIGHT // 2 + 300],
                  [WIN_WIDTH // 2 - BUTTONWIDTH // 2, WIN_HEIGHT // 2 - BUTTONHEIGHT // 2 - 300],
                  [WIN_WIDTH // 2 - BUTTONWIDTH // 2, WIN_HEIGHT // 2 - BUTTONHEIGHT // 2 - 100],
                  [WIN_WIDTH // 2 - BUTTONWIDTH // 2, WIN_HEIGHT // 2 - BUTTONHEIGHT // 2 + 100],
                  [WIN_WIDTH // 2 - BUTTONWIDTH // 2, WIN_HEIGHT // 2 - BUTTONHEIGHT // 2 + 300]]

TEXTMENUPOSITION = (WIN_WIDTH // 2, 50)

MAP = []

with open("maps.json", 'r') as f:
    json_maps = json.load(f)
    MAP.append(json_maps["MAP1"])
    MAP.append(json_maps["MAP2"])
    MAP.append(json_maps["MAP3"])

# number of fake nodes on which ghosts can seek their way to the pacman
GRAPHLENGTH = [301, 312, 349]
POINTSNUMBER = [246, 264, 309]
